name:                dbmigrations
version:             0.1.0.0
github:              "githubuser/dbmigrations"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dbmigrations#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- unix
- bytestring
- fgl
- process
- time
- HUnit
- containers
- text
- hasql
- configurator
- yaml-light
- filepath
- directory
- vty

library:
  source-dirs:       src
  ghc-options:
    - -Wall
    - -j
